app/base/models.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask_login import UserMixin
from sqlalchemy import Binary, Column, Integer, String

from app import db, login_manager

from app.base.util import hash_pass

class User(db.Model, UserMixin):

    __tablename__ = 'User'

    id = Column(Integer, primary_key=True)
    username = Column(String, unique=True)
    email = Column(String, unique=True)
    password = Column(Binary)

    def __init__(self, **kwargs):
        for property, value in kwargs.items():
            # depending on whether value is an iterable or not, we must
            # unpack it's value (when **kwargs is request.form, some values
            # will be a 1-element list)
            if hasattr(value, '__iter__') and not isinstance(value, str):
                # the ,= unpack of a singleton fails PEP8 (travis flake8 test)
                value = value[0]

            if property == 'password':
                value = hash_pass( value ) # we need bytes here (not plain str)
                
            setattr(self, property, value)

    def __repr__(self):
        return str(self.username)


@login_manager.user_loader
def user_loader(id):
    return User.query.filter_by(id=id).first()

@login_manager.request_loader
def request_loader(request):
    username = request.form.get('username')
    user = User.query.filter_by(username=username).first()
    return user if user else None

app/base/forms.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import InputRequired, Email, DataRequired

## login and registration

class LoginForm(FlaskForm):
    username = StringField    ('Username', id='username_login'   , validators=[DataRequired()])
    password = PasswordField('Password', id='pwd_login'        , validators=[DataRequired()])

class CreateAccountForm(FlaskForm):
    username = StringField('Username'     , id='username_create' , validators=[DataRequired()])
    email    = StringField('Email'        , id='email_create'    , validators=[DataRequired(), Email()])
    password = PasswordField('Password' , id='pwd_create'      , validators=[DataRequired()])

app/base/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'base_blueprint',
    __name__,
    url_prefix='',
    template_folder='templates',
    static_folder='static'
)

app/base/routes.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import jsonify, render_template, redirect, request, url_for
from flask_login import (
    current_user,
    login_required,
    login_user,
    logout_user
)

from app import db, login_manager
from app.base import blueprint
from app.base.forms import LoginForm, CreateAccountForm
from app.base.models import User

from app.base.util import verify_pass

@blueprint.route('/')
def route_default():
    #return redirect(url_for('base_blueprint.login'))
    return render_template('accounts/welcome.html')
    
    
## Login & Registration

@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm(request.form)
    if 'login' in request.form:
        
        # read form data
        username = request.form['username']
        password = request.form['password']

        # Locate user
        user = User.query.filter_by(username=username).first()
        
        # Check the password
        if user and verify_pass( password, user.password):

            login_user(user)
            return redirect(url_for('base_blueprint.login'))
            #return redirect(url_for('home_blueprint.index'))

        # Something (user or pass) is not ok
        return render_template( 'accounts/login.html', msg='Wrong user or password', form=login_form)

    if not current_user.is_authenticated:
        return render_template( 'accounts/login.html',
                                form=login_form)
    return redirect(url_for('home_blueprint.index'))

@blueprint.route('/register', methods=['GET', 'POST'])
def register():
    login_form = LoginForm(request.form)
    create_account_form = CreateAccountForm(request.form)
    if 'register' in request.form:

        username  = request.form['username']
        email     = request.form['email'   ]

        # Check usename exists
        user = User.query.filter_by(username=username).first()
        if user:
            return render_template( 'accounts/register.html', 
                                    msg='Username already registered',
                                    success=False,
                                    form=create_account_form)

        # Check email exists
        user = User.query.filter_by(email=email).first()
        if user:
            return render_template( 'accounts/register.html', 
                                    msg='Email already registered', 
                                    success=False,
                                    form=create_account_form)

        # else we can create the user
        user = User(**request.form)
        db.session.add(user)
        db.session.commit()

        return render_template( 'accounts/register.html', 
                                msg='User created please <a href="/login">login</a>', 
                                success=True,
                                form=create_account_form)

    else:
        return render_template( 'accounts/register.html', form=create_account_form)

@blueprint.route('/logout')
def logout():
    logout_user()
    return render_template('accounts/welcome.html')

## Errors

@login_manager.unauthorized_handler
def unauthorized_handler():
    return render_template('page-403.html'), 403

@blueprint.errorhandler(403)
def access_forbidden(error):
    return render_template('page-403.html'), 403

@blueprint.errorhandler(404)
def not_found_error(error):
    return render_template('page-404.html'), 404

@blueprint.errorhandler(500)
def internal_error(error):
    return render_template('page-500.html'), 500

app/base/templates/accounts/login.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Login {% endblock %}

{% block content %}   

    <div class="auth-wrapper">
        <div class="auth-content">
            <div class="auth-bg">
                <span class="r"></span>
                <span class="r s"></span>
                <span class="r s"></span>
                <span class="r"></span>
            </div>
            <div class="card">
                <div class="card-body text-center">
                    <div class="mb-4">
                        <!-- <i class="feather icon-unlock auth-icon"></i> -->
                        <img src="../static\assets/images/mlogo.png">
                    </div>
                    <h3 class="mb-4 modern">Login</h3>

                    <span class="mb-0 text-muted modern">
                        {% if msg %}
                            {{ msg | safe }}
                        {% else %}
                            Add your credentials
                        {% endif %} 
                    </span>

                    <br />
                    <br />
                    
                    <form role="form" method="post" action="">

                        {{ form.hidden_tag() }}                    

                        <div class="input-group mb-3 modern">
                            {{ form.username(placeholder="Username", class="form-control") }}
                        </div>
                        
                        <div class="input-group mb-4 modern">
                            {{ form.password(placeholder="Password", class="form-control", type="password") }}
                        </div>
                        
                        <div class="form-group text-left">
                            <div class="checkbox checkbox-fill d-inline">
                                <input type="checkbox" name="checkbox-fill-1" id="checkbox-fill-a1" checked="">
                                <label for="checkbox-fill-a1" class="cr modern"> Save Details</label>
                            </div>
                        </div>
                        <button type="submit" name="login" class="btn btn-primary shadow-2 mb-4 modern">Login</button>

                    </form>

                    <p class="mb-0 text-muted modern">Don’t have an account? <a href="{{ url_for('base_blueprint.register') }}" >Signup</a></p>
                    <br />
                    <!-- <p class="mb-2 text-muted">
                        &copy; <a target="_blank" href="https://bit.ly/37fF9RT">CodedThemes</a> 
                        - <a target="_blank" 
                             href="https://appseed.us/admin-dashboards/flask-dashboard-dattaable">Flask Datta Able</a>.
                    </p> -->
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

app/base/templates/accounts/register.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Login {% endblock %}

{% block content %}   

    <div class="auth-wrapper">
        <div class="auth-content">
            <div class="auth-bg">
                <span class="r"></span>
                <span class="r s"></span>
                <span class="r s"></span>
                <span class="r"></span>
            </div>
            <div class="card">
                <div class="card-body text-center">
                    <div class="mb-4">
                        <!-- <i class="feather icon-user-plus auth-icon"></i> -->
                        <img src="../static\assets/images/mlogo.png">
                    </div>
                    <h3 class="mb-4 modern">Sign up</h3>

                    <span class="mb-0 text-muted modern">
                        {% if msg %}
                            {{ msg | safe }}
                        {% else %}
                            Add your credentials
                        {% endif %} 
                    </span>

                    <br />
                    <br />

                    <!-- Hide the form on success -->
                    {% if not success %}
                        <form role="form" method="post" action="">

                            {{ form.hidden_tag() }}                    

                            <div class="input-group mb-3 modern">
                                {{ form.username(placeholder="Username", class="form-control") }}
                            </div>
                            
                            <div class="input-group mb-3 modern">
                                {{ form.email(placeholder="Email", class="input form-control", type="email") }}
                            </div>

                            <div class="input-group mb-4 modern">
                                {{ form.password(placeholder="Password", class="form-control", type="password") }}
                            </div>
                            
                            <div class="form-group text-left">
                                <div class="checkbox checkbox-fill d-inline">
                                    <input type="checkbox" name="checkbox-fill-1" id="checkbox-fill-a1" checked="">
                                    <label for="checkbox-fill-a1" class="cr modern"> Agree with <a href="#">terms</a></label>
                                </div>
                            </div>
                            <button type="submit" name="register" class="btn btn-primary shadow-2 mb-4 modern">Register</button>

                        </form>
                        
                        <p class="mb-0 text-muted modern">Already have an account? <a href="{{ url_for('base_blueprint.login') }}">Login</a></p>
                        <br />
                    {% endif %}

                    <!-- <p class="mb-2 text-muted">
                        &copy; <a target="_blank" href="https://bit.ly/37fF9RT">CodedThemes</a> 
                        - <a target="_blank" 
                             href="https://appseed.us/admin-dashboards/flask-dashboard-dattaable">Flask Datta Able</a>.
                    </p> -->
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

app/base/templates/accounts/welcome.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Welcome {% endblock title %} 

{% block content %} 

    <div class="auth-wrapper">
        <div class="auth-content">
            <div class="auth-bg">
                <span class="r"></span> 
                <span class="r s"></span> 
                <span class="r s"></span> 
                <span class="r"></span> 
            </div> 
            <div class="card">
                <div class="card-body text-center">
                    <div class="mb-4">
                   <!--  <i class="feather icon-unlock auth-icon"></i>  -->
                        <img src="../static\assets/images/mlogo.png">
                    </div>
                    <h3 class="mb-4 modern">Welcome</h3> 

                    <span class="mb-4 modern text-muted">
                        {% if msg %} 
                            {{ msg | safe }} 
                        {% else %} 
                            New Mother
                        {% endif %} 
                    </span>

                    <br />
                    <br />

                    <form method="POST" action="/login">

                        <button onclick="location.href='/login'" class="modern btn btn-primary shadow-2 mb-4">Login</button>

                    </form>

                    <form role="form" method="POST" action="/register">

                        <button onclick="location.href='/register'" class="modern btn btn-primary-2 shadow-2 mb-4">Register</button>

                    </form>

                </div>
            </div>
        </div>
    </div>
{% endblock content %} 

app/base/templates/includes/navigation.html
<!-- NOT IMPLEMENTED -->

app/base/templates/includes/scripts.html
    <!-- Required Js -->
    <script src="/static/assets/js/vendor-all.min.js"></script>
    <script src="/static/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="/static/assets/js/pcoded.min.js"></script>

app/base/templates/includes/sidebar.html
    <nav class="pcoded-navbar">
        <div class="navbar-wrapper">
            <div class="navbar-brand header-logo">
                
                <div class="b-bg">
                    <img src="../static\assets/images/mlogo.png" style="width: 60%; height 60%; border 10px solid #000;">
                </div>
                <span class="b-title f-22">Maternity Tracker</span>
            </div>    
            <!--<div class="mobile-menu" id="mobile-collapse" href="javascript:"><span></span>
            </div>-->
            <div class="navbar-content scroll-div">
                <ul class="nav pcoded-inner-navbar">
                    <li class="nav-item pcoded-menu-caption">
                        <label>Navigation</label>
                    </li>
                    <li data-username="dashboard Default Ecommerce CRM Analytics Crypto Project" 
                        class="nav-item {% if 'index' in segment %} active {% endif %}">
                        <a href="/index.html" class="nav-link "><span class="pcoded-micon"><i class="feather icon-home"></i></span><span class="pcoded-mtext">Dashboard</span></a>
                    </li>
                    <li class="nav-item pcoded-menu-caption">
                        <label>Symptoms</label>
                    </li>
                    <!--<li data-username="basic components Button Alert Badges breadcrumb Paggination progress Tooltip popovers Carousel Cards Collapse Tabs pills Modal Grid System Typography Extra Shadows Embeds" class="nav-item pcoded-hasmenu">
                        <a href="javascript:" class="nav-link "><span class="pcoded-micon"><i class="feather icon-box"></i></span><span class="pcoded-mtext">Components</span></a>
                        <ul class="pcoded-submenu">
                            <li class=""><a href="/ui-button.html" class="">Button</a></li>
                            <li class=""><a href="/ui-badges.html" class="">Badges</a></li>
                            <li class=""><a href="/ui-breadcrumb-pagination.html" class="">Breadcrumb & paggination</a></li>
                            <li class=""><a href="/ui-collapse.html" class="">Collapse</a></li>
                            <li class=""><a href="/ui-tabs.html" class="">Tabs & pills</a></li>
                            <li class=""><a href="/ui-typography.html" class="">Typography</a></li>
                            <li class=""><a href="/ui-icons.html" class="">Feather<span class="pcoded-badge label label-danger">NEW</span></a></li>
                        </ul>
                    </li> -->
                    <li class="nav-item pcoded-menu-caption">
                        <label>Foods</label>
                    </li>
                    <!--<li data-username="form elements advance componant validation masking wizard picker select" 
                        class="nav-item {% if 'ui-forms' in segment %} active {% endif %}">
                        <a href="/ui-forms.html" class="nav-link "><span class="pcoded-micon"><i class="feather icon-file-text"></i></span><span class="pcoded-mtext">Form elements</span></a>
                    </li>
                    <li data-username="Table bootstrap datatable footable" 
                        class="nav-item {% if 'ui-tables' in segment %} active {% endif %}">
                        <a href="/ui-tables.html" class="nav-link "><span class="pcoded-micon"><i class="feather icon-server"></i></span><span class="pcoded-mtext">Table</span></a>
                    </li>-->
                    <li class="nav-item pcoded-menu-caption">
                        <label>Physical Activitys</label>
                    </li>
                    <!--<li data-username="Charts Morris" 
                        class="nav-item {% if 'charts-morris' in segment %} active {% endif %}">
                        <a href="/charts-morris.html" class="nav-link "><span class="pcoded-micon"><i class="feather icon-pie-chart"></i></span><span class="pcoded-mtext">Chart</span></a></li>
                    <li data-username="Maps Google" 
                         class="nav-item {% if 'maps-google' in segment %} active {% endif %}">
                        <a href="/maps-google.html" class="nav-link "><span class="pcoded-micon"><i class="feather icon-map"></i></span><span class="pcoded-mtext">Maps</span></a></li>-->
                    <li class="nav-item pcoded-menu-caption">
                        <label>Medications</label>
                    </li>
                    <li data-username="Authentication Sign up Sign in reset password Change password Personal information profile settings map form subscribe" class="nav-item pcoded-hasmenu">
                        <a href="javascript:" class="nav-link "><span class="pcoded-micon"><i class="feather icon-lock"></i></span><span class="pcoded-mtext">Authentication</span></a>
                        <ul class="pcoded-submenu">
                            <li class=""><a href="/auth-reset-pass.html" class="">Reset Pass</a></li>
                            <li class=""><a href="/login.html" class="">Login (template)</a></li>
                            <li class=""><a href="/register.html" class="">Register (template)</a></li>
                        </ul>
                    </li>
                    <!--<li data-username="Sample Page" 
                        class="nav-item {% if 'page-blank' in segment %} active {% endif %}">
                        <a href="/page-blank.html" class="nav-link"><span class="pcoded-micon"><i class="feather icon-sidebar"></i></span><span class="pcoded-mtext">Sample page</span></a></li>
                    <li data-username="Sample Page" class="nav-item"><a href="/page-404.html" class="nav-link"><span class="pcoded-micon"><i class="feather icon-sidebar"></i></span><span class="pcoded-mtext">Error 404</span></a></li>-->

                    <li data-username="Disabled Menu" class="nav-item">
                        <a href="{{ url_for('base_blueprint.logout') }}" class="nav-link">
                            <span class="pcoded-micon"><i class="feather icon-power"></i></span><span class="pcoded-mtext">Logout</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

app/base/templates/layouts/base-fullscreen.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>
        Flask Datta Able - {% block title %}{% endblock %} | AppSeed
    </title>
    <!-- HTML5 Shim and Respond.js IE10 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 10]>
		<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
		<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
    <!-- Meta -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="canonical" href="https://appseed.us/admin-dashboards/flask-dashboard-dattaable">
    
    <meta name="description" content="Datta Able Bootstrap admin template made using Bootstrap 4 and it has huge amount of ready made feature, UI components, pages which completely fulfills any dashboard needs." />
    <meta name="keywords" content="admin templates, bootstrap admin templates, bootstrap 4, dashboard, dashboard templets, sass admin templets, html admin templates, responsive, bootstrap admin templates free download,premium bootstrap admin templates, datta able, datta able bootstrap admin template, free admin theme, free dashboard template"/>
    <meta name="author" content="CodedThemes"/>

    <!-- Favicon icon -->
    <link rel="icon" href="/static/assets/images/favicon.ico" type="image/x-icon">
    <!-- fontawesome icon -->
    <link rel="stylesheet" href="/static/assets/fonts/fontawesome/css/fontawesome-all.min.css">
    <!-- animation css -->
    <link rel="stylesheet" href="/static/assets/plugins/animation/css/animate.min.css">
    <!-- vendor css -->
    <link rel="stylesheet" href="/static/assets/css/style.css">

    <!-- Specific CSS goes HERE -->
    {% block stylesheets %}{% endblock stylesheets %}

</head>

<body>
    
    {% block content %}

    <nav> 
        <h1><a href="/accounts/welcome.html">Maternity Tracker</a></h1>
    </nav>
    {% endblock content %}

    {% include 'includes/scripts.html' %}

    <!-- Specific Page JS goes HERE  -->
    {% block javascripts %}{% endblock javascripts %}    

</body>
</html>

app/base/templates/layouts/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>
        Flask Datta Able - {% block title %}{% endblock %} | AppSeed
    </title>
    <!-- HTML5 Shim and Respond.js IE10 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 10]>
		<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
		<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
    <!-- Meta -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="canonical" href="https://appseed.us/admin-dashboards/flask-dashboard-dattaable">
    
    <meta name="description" content="Datta Able Bootstrap admin template made using Bootstrap 4 and it has huge amount of ready made feature, UI components, pages which completely fulfills any dashboard needs." />
    <meta name="keywords" content="admin templates, bootstrap admin templates, bootstrap 4, dashboard, dashboard templets, sass admin templets, html admin templates, responsive, bootstrap admin templates free download,premium bootstrap admin templates, datta able, datta able bootstrap admin template, free admin theme, free dashboard template"/>
    <meta name="author" content="CodedThemes"/>

    <!-- Favicon icon -->
    <link rel="icon" href="/static/assets/images/favicon.ico" type="image/x-icon">
    <!-- fontawesome icon -->
    <link rel="stylesheet" href="/static/assets/fonts/fontawesome/css/fontawesome-all.min.css">
    <!-- animation css -->
    <link rel="stylesheet" href="/static/assets/plugins/animation/css/animate.min.css">
    <!-- vendor css -->
    <link rel="stylesheet" href="/static/assets/css/style.css">

    <!-- Specific CSS goes HERE -->
    {% block stylesheets %}{% endblock stylesheets %}

</head>

<body>

    <!-- [ Pre-loader ] start -->
    <div class="loader-bg">
        <div class="loader-track">
            <div class="loader-fill"></div>
        </div>
    </div>    
    
    <!-- Top Bar -->
    {% include 'includes/navigation.html' %}

    <!-- SideBar -->
    {% include 'includes/sidebar.html' %}

    <div class="pcoded-main-container">
        <div class="pcoded-wrapper">

            {% block content %}{% endblock content %}

        </div>
    </div>

    {% include 'includes/scripts.html' %}

    <!-- Specific Page JS goes HERE  -->
    {% block javascripts %}{% endblock javascripts %}

</body>
</html>